name: UI Automation Test (IND)

on:
  schedule: 
   - cron: "30 1 * * 2,4"
  workflow_dispatch: # trigger manually or by schedule

jobs:
  set-browser:
    runs-on: self-hosted
    outputs:
      browser: ${{ steps.set-browser.outputs.browser }}
    steps:
      - name: Set browser by day
        id: set-browser
        run: |
          $day = (Get-Date).DayOfWeek.value__
          if ($day -eq 2) {
            echo "browser=chrome" >> $env:GITHUB_OUTPUT
          } elseif ($day -eq 4) {
            echo "browser=msedge" >> $env:GITHUB_OUTPUT
          } else {
            echo "browser=chromium" >> $env:GITHUB_OUTPUT
          }

  run-ui-ind:
    needs: set-browser  # 👈 wait for set-browser
    uses: LintraMax/Playwright-Automation/.github/workflows/playwright_auto.yml@main # 👈 calls your Playwright workflow
    with:
      testType: "UI Tests"
      region: IND
      browser: ${{ needs.set-browser.outputs.browser }}
    secrets: inherit 
